export const COURSE_TITLE_SET = 'COURSE_TITLE_SET';

export const COURSE_INSTITUTION_SET = 'COURSE_INSTITUTION_SET';

export const COURSE_DATE_FROM_SET = 'COURSE_DATE_FROM_SET';

export const COURSE_DATE_TO_SET = 'COURSE_DATE_TO_SET';

export const COURSE_ADDED = 'COURSE_ADDED';
