export const JOB_TITLE_SET = 'JOB_TITLE_SET';

export const PHOTO_UPLOAD_STARTED = 'PHOTO_UPLOAD_STARTED';

export const PHOTO_UPLOADED = 'PHOTO_UPLOADED';

export const PHOTO_NOT_UPLOADED = 'PHOTO_NOT_UPLOADED';

export const FIRST_NAME_SET = 'FIRST_NAME_SET';

export const LAST_NAME_SET = 'LAST_NAME_SET';

export const EMAIL_SET = 'EMAIL_SET';

export const PHONE_SET = 'PHONE_SET';

export const COUNTRY_SET = 'COUNTRY_SET';

export const CITY_SET = 'CITY_SET';

export const ADDRESS_SET = 'ADDRESS_SET';

export const POSTAL_CODE_SET = 'POSTAL_CODE_SET';

export const DRIVING_LICENSE_SET = 'DRIVING_LICENSE_SET';

export const NATIONALITY_SET = 'NATIONALITY_SET';

export const PLACE_OF_BIRTH_SET = 'PLACE_OF_BIRTH_SET';

export const DATE_OF_BIRTH_SET = 'DATE_OF_BIRTH_SET';
