export const EDUCATION_SCHOOL_SET = 'EDUCATION_SCHOOL_SET';

export const EDUCATION_DEGREE_SET = 'EDUCATION_DEGREE_SET';

export const EDUCATION_CITY_SET = 'EDUCATION_CITY_SET';

export const EDUCATION_DESCRIPTION_SET = 'EDUCATION_DESCRIPTION_SET';

export const EDUCATION_DATE_FROM_SET = 'EDUCATION_DATE_FROM_SET';

export const EDUCATION_DATE_TO_SET = 'EDUCATION_DATE_TO_SET';

export const EDUCATION_ADDED = 'EDUCATION_ADDED';
