export const EMPLOYMENT_JOB_TITLE_SET = 'EMPLOYMENT_JOB_TITLE_SET';

export const EMPLOYMENT_EMPLOYER_SET = 'EMPLOYMENT_EMPLOYER_SET';

export const EMPLOYMENT_CITY_SET = 'EMPLOYMENT_CITY_SET';

export const EMPLOYMENT_DATE_FROM_SET = 'EMPLOYMENT_DATE_FROM_SET';

export const EMPLOYMENT_DATE_TO_SET = 'EMPLOYMENT_DATE_TO_SET';

export const EMPLOYMENT_DESCRIPTION_SET = 'EMPLOYMENT_DESCRIPTION_SET';

export const EMPLOYMENT_ADDED = 'EMPLOYMENT_ADDED';
