export const MODAL_DISPLAYED = 'MODAL_DISPLAYED';

export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';

export const DOCUMENT_TITLE_UPDATED = 'DOCUMENT_TITLE_UPDATED';

export const TEMPLATE_CHOOSED = 'TEMPLATE_CHOOSED';

export const LOADER_DISPLAYED = 'LOADER_DISPLAYED';